name: shoppy
description: A new Flutter application.



version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3
  carousel_pro: ^1.0.0
  firebase_auth: ^0.16.1
  cloud_firestore: ^0.13.7
  google_sign_in: ^4.5.1
  shared_preferences: ^0.5.7+3
  fluttertoast: ^4.0.1



dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:


  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/c1.jpg
    - images/m1.jpeg
    - images/m2.jpg
    - images/w1.jpeg
    - images/w3.jpeg
    - images/w4.jpeg
    - images/cats/tshirt.png
    - images/cats/shoe.png
    - images/cats/jeans.png
    - images/cats/informal.png
    - images/cats/formal.png
    - images/cats/dress.png
    - images/cats/accessories.png
    - images/products/blazer1.jpeg
    - images/products/blazer2.jpeg
    - images/products/dress1.jpeg
    - images/products/dress2.jpeg
    - images/products/hills1.jpeg
    - images/products/hills2.jpeg
    - images/products/pants1.jpg
    - images/products/pants2.jpeg
    - images/products/shoe1.jpg
    - images/products/skt1.jpeg
    - images/products/skt2.jpeg
    - images/background.jpg
    - images/logo.png


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages


  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
